#!/bin/sh
#
# 	Usage : newLatexDoc <Directory>
# 	Desc  : This script generates a new latexDocument based on this template by cloning the template repository.
#
git clone /home/daminetreg/workspace/latex/template/ $1
cd $1
rm newLatexDoc
rm README
mv src/* .
mv src/.gitignore .gitignore
rmdir src
git checkout -b $1
git add . -A
git commit -m "New Latex Report - $1"
git remote rm origin
